# Site Settings
title: Railson Ramés | Website
email: railson.rames@gmail.com
description: Minha página web, um ponto de compartilhamento
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://railson.net" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Railson Ramés
user_description: Programeiro, banqueiro e de vez em quando analista de T.I.
disqus_username: railsonrams

# Social Media
# Remove the item if you don't need it
github_username: railsonrames
facebook_username: railson.rames
twitter_username: centrinobr
instagram_username: centrinobr
linkedin_username: railson
medium_username: railson.rames

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Início
    url: /
  - title: Sobre
    url: /about/
  - title: Contato
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
